feature/rsk-address-rpc
santicomp2014/rif-communications-pubsub-python-grpc pull request #10
Opened 2020-12-10 14:40 UTC by mauricioirace

Changes:
- Replace SendMessageToTopic calls by SendMessageToRskAddress

2020-12-10 14:47 UTC, santicomp2014 requested changes
Minor change to the proto, everything else is ok.
Thanks

2020-12-10 14:47 UTC, santicomp2014 commented on proto/api.proto
> +    string address = 1;
This should use the same message as `RskAddress`
`RskAddress address = 1`

2020-12-10 17:46 UTC, santicomp2014 approved these changes
LGTM thanks for the change

2020-12-10 20:50 UTC, marcosmartinez7 approved these changes

2020-12-15 14:14 UTC, mortelli approved these changes
thanks @mauricioirace for this :+1: 

looks good from my end.

i might have some changes to suggest based on whether or not i get to try out these scripts (and if so, based also on whether i have any changes to suggest).

for now we're good to go

2020-12-15 14:16 UTC, merged